### PR TITLE
Smareng 72 03 branch

### PR DESCRIPTION
**Pull request by RantiE**
Moved changes to the data model to v1.1 and reverted changes to v1.0 files. 
Added an optional barcode field to the package Tag Group.

### CODE REVIEW

**Review by geoffmartin-adlink — APPROVED** [review]
See newer comment.

**Review by geoffmartin-adlink — CHANGES_REQUESTED** [review]
While the changes look good the PR needs to be recreated to merge to develop branch instead of master.

**Comment by RantiE** [comment]
> While the changes look good the PR needs to be recreated to merge to develop branch instead of master.

I think I have changed it to the proper base now

**Review by geoffmartin-adlink — APPROVED** [review]
Accepted onto develop.

**Pull request merged**
